"""Create all EMR and research case tables

Revision ID: ee534ad0ed01
Revises: 
Create Date: 2025-11-13 13:20:31.871431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ee534ad0ed01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_documents_document_category')
        batch_op.drop_index('ix_patient_documents_document_date')
        batch_op.drop_index('ix_patient_documents_document_type')
        batch_op.drop_index('ix_patient_documents_patient_id')
        batch_op.drop_index('ix_patient_documents_uploaded_at')
        batch_op.drop_index('ix_patient_documents_visit_id')

    op.drop_table('patient_documents')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_admission_date')
        batch_op.drop_index('ix_patients_city')
        batch_op.drop_index('ix_patients_created_at')
        batch_op.drop_index('ix_patients_date_of_birth')
        batch_op.drop_index('ix_patients_email')
        batch_op.drop_index('ix_patients_external_id')
        batch_op.drop_index('ix_patients_first_name')
        batch_op.drop_index('ix_patients_insurance_primary_type')
        batch_op.drop_index('ix_patients_is_deleted')
        batch_op.drop_index('ix_patients_last_name')
        batch_op.drop_index('ix_patients_mrn')
        batch_op.drop_index('ix_patients_patient_status')
        batch_op.drop_index('ix_patients_phone_primary')
        batch_op.drop_index('ix_patients_state')
        batch_op.drop_index('ix_patients_zip_code')

    op.drop_table('patients')
    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_visits_patient_id')
        batch_op.drop_index('ix_patient_visits_visit_date')
        batch_op.drop_index('ix_patient_visits_visit_type')

    op.drop_table('patient_visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_visits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('visit_date', sa.DATE(), nullable=False),
    sa.Column('visit_type', sa.VARCHAR(), nullable=False),
    sa.Column('visit_reason', sa.VARCHAR(), nullable=True),
    sa.Column('chief_complaint', sa.TEXT(), nullable=True),
    sa.Column('diagnosis', sa.VARCHAR(), nullable=True),
    sa.Column('treatment_plan', sa.TEXT(), nullable=True),
    sa.Column('attending_physician', sa.VARCHAR(), nullable=True),
    sa.Column('consulting_physicians', sa.VARCHAR(), nullable=True),
    sa.Column('vital_signs', sqlite.JSON(), nullable=True),
    sa.Column('billing_codes', sqlite.JSON(), nullable=True),
    sa.Column('visit_cost', sa.FLOAT(), nullable=True),
    sa.Column('visit_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.create_index('ix_patient_visits_visit_type', ['visit_type'], unique=False)
        batch_op.create_index('ix_patient_visits_visit_date', ['visit_date'], unique=False)
        batch_op.create_index('ix_patient_visits_patient_id', ['patient_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mrn', sa.VARCHAR(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('preferred_name', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('sex', sa.VARCHAR(), nullable=False),
    sa.Column('gender_identity', sa.VARCHAR(), nullable=True),
    sa.Column('pronouns', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone_primary', sa.VARCHAR(), nullable=True),
    sa.Column('phone_secondary', sa.VARCHAR(), nullable=True),
    sa.Column('phone_emergency', sa.VARCHAR(), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=False),
    sa.Column('marital_status', sa.VARCHAR(), nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(), nullable=True),
    sa.Column('race', sa.VARCHAR(), nullable=True),
    sa.Column('ethnicity', sa.VARCHAR(), nullable=True),
    sa.Column('religion', sa.VARCHAR(), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(), nullable=True),
    sa.Column('emergency_contact_relationship', sa.VARCHAR(), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('emergency_contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('blood_type', sa.VARCHAR(), nullable=True),
    sa.Column('height_cm', sa.FLOAT(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('bmi', sa.FLOAT(), nullable=True),
    sa.Column('primary_care_physician', sa.VARCHAR(), nullable=True),
    sa.Column('primary_care_clinic', sa.VARCHAR(), nullable=True),
    sa.Column('referring_physician', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_primary_provider', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_primary_policy_number', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_primary_group_number', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_primary_type', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_secondary_provider', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_secondary_policy_number', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_secondary_group_number', sa.VARCHAR(), nullable=True),
    sa.Column('insurance_secondary_type', sa.VARCHAR(), nullable=True),
    sa.Column('allergies', sqlite.JSON(), nullable=True),
    sa.Column('medications', sqlite.JSON(), nullable=True),
    sa.Column('chronic_conditions', sqlite.JSON(), nullable=True),
    sa.Column('past_surgeries', sqlite.JSON(), nullable=True),
    sa.Column('family_history', sqlite.JSON(), nullable=True),
    sa.Column('social_history', sqlite.JSON(), nullable=True),
    sa.Column('chief_complaint', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('patient_status', sa.VARCHAR(), nullable=False),
    sa.Column('admission_date', sa.DATE(), nullable=True),
    sa.Column('discharge_date', sa.DATE(), nullable=True),
    sa.Column('deceased_date', sa.DATE(), nullable=True),
    sa.Column('custom_fields', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_zip_code', ['zip_code'], unique=False)
        batch_op.create_index('ix_patients_state', ['state'], unique=False)
        batch_op.create_index('ix_patients_phone_primary', ['phone_primary'], unique=False)
        batch_op.create_index('ix_patients_patient_status', ['patient_status'], unique=False)
        batch_op.create_index('ix_patients_mrn', ['mrn'], unique=1)
        batch_op.create_index('ix_patients_last_name', ['last_name'], unique=False)
        batch_op.create_index('ix_patients_is_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('ix_patients_insurance_primary_type', ['insurance_primary_type'], unique=False)
        batch_op.create_index('ix_patients_first_name', ['first_name'], unique=False)
        batch_op.create_index('ix_patients_external_id', ['external_id'], unique=False)
        batch_op.create_index('ix_patients_email', ['email'], unique=False)
        batch_op.create_index('ix_patients_date_of_birth', ['date_of_birth'], unique=False)
        batch_op.create_index('ix_patients_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_patients_city', ['city'], unique=False)
        batch_op.create_index('ix_patients_admission_date', ['admission_date'], unique=False)

    op.create_table('patient_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(), nullable=False),
    sa.Column('document_title', sa.VARCHAR(), nullable=False),
    sa.Column('document_description', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('file_url', sa.VARCHAR(), nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('document_date', sa.DATE(), nullable=True),
    sa.Column('document_category', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('is_confidential', sa.BOOLEAN(), nullable=False),
    sa.Column('access_level', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['patient_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.create_index('ix_patient_documents_visit_id', ['visit_id'], unique=False)
        batch_op.create_index('ix_patient_documents_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.create_index('ix_patient_documents_patient_id', ['patient_id'], unique=False)
        batch_op.create_index('ix_patient_documents_document_type', ['document_type'], unique=False)
        batch_op.create_index('ix_patient_documents_document_date', ['document_date'], unique=False)
        batch_op.create_index('ix_patient_documents_document_category', ['document_category'], unique=False)

    # ### end Alembic commands ###
